// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIvoQ-zB8hIzTea8RSu9G9p4ug5FvwOeM',
    appId: '1:250684178712:web:4f98ab17a8dbb571e51e6d',
    messagingSenderId: '250684178712',
    projectId: 'astikasencryptdecrypt',
    authDomain: 'astikasencryptdecrypt.firebaseapp.com',
    storageBucket: 'astikasencryptdecrypt.appspot.com',
    measurementId: 'G-M86Y46K270',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRzV-sThHvVYPiraXowNrvz6DLV5VtsM',
    appId: '1:250684178712:android:58cd2fd63337c528e51e6d',
    messagingSenderId: '250684178712',
    projectId: 'astikasencryptdecrypt',
    storageBucket: 'astikasencryptdecrypt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-AvkPd8m5eMx6w5cNVW6mDuDaWXJxLPE',
    appId: '1:250684178712:ios:0c5fbce9fbb8e1a9e51e6d',
    messagingSenderId: '250684178712',
    projectId: 'astikasencryptdecrypt',
    storageBucket: 'astikasencryptdecrypt.appspot.com',
    iosBundleId: 'com.example.astikasencryptdecrypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-AvkPd8m5eMx6w5cNVW6mDuDaWXJxLPE',
    appId: '1:250684178712:ios:c39419c60ef4c42ee51e6d',
    messagingSenderId: '250684178712',
    projectId: 'astikasencryptdecrypt',
    storageBucket: 'astikasencryptdecrypt.appspot.com',
    iosBundleId: 'com.example.astikasencryptdecrypt.RunnerTests',
  );
}
